# Populations

In calculating over weighted survey microdata, we use the Family Resources Survey. This isn't redistributable, but is available to academics. We use the package ```frs``` to convert the source TAB files into OpenFisca-compatible CSV files.

## Prerequisite: install and initialise ```frs```

First, install and initialise the package ```frs``` (via ```pip install frs```):

In [2]:
!frs status

FRS status:
	FRS TAB files stored?				Yes
	FRS OpenFisca-UK input files generated?		Yes
	OpenFisca-UK input files outdated?		No (files generated with current version, 0.2.0)

The FRS package needs to be pointed to a folder containing the source TAB files for a year of the FRS. Command-line hints are provided:

In [11]:
!frs --help

usage: frs [-h] [--path PATH] {status,gen,regen}

Utility for managing Family Resources Survey microdata

positional arguments:
  {status,gen,regen}  The action to take on stored data

optional arguments:
  -h, --help          show this help message and exit
  --path PATH         The path to the FRS data

## Using ```PopulationSim```

The helper class ```PopulationSim``` uses the FRS package to load the input data:

In [5]:
from openfisca_uk import PopulationSim

sim = PopulationSim()

This helper class contains an OpenFisca Simulation object in ```sim.model```; the ```PopulationSim``` class provides some functions such as mapping between entity types, effective marginal tax rate calculation and DataFrame generation.

For example, we can generate a DataFrame containing all the variables for the ```person``` entity:

In [10]:
import pandas as pd
person_df = sim.entity_df(entity="person")
person_df.describe()

,adult_weight,age,care_hours,hours,index,is_SP_age,is_WA_adult,num_rooms_in_household,person_id,person_region,...,savings_starter_allowance_deduction,taxable_income,taxable_income_deductions,total_tax,trading_deduction,unused_personal_allowance,NI,NI_class_1,NI_class_2,NI_class_4
count,43087.000000,43087.000000,43087.000000,43087.000000,43087.0,43087.000000,43087.000000,43087.000000,4.308700e+04,43087.000000,...,43087.000000,4.308700e+04,43087.000000,4.308700e+04,43087.000000,43087.000000,43087.000000,43087.000000,43087.000000,43087.000000
mean,1196.495728,41.514309,1.940168,15.404361,0.0,0.218952,0.557384,5.722561,1.096032e+06,5.973379,...,58.392147,1.681093e+04,7166.048340,3.506760e+03,85.381966,5442.554688,822.033203,743.129822,0.126000,72.351021
std,1175.479980,23.953661,10.537108,19.480444,0.0,0.413466,0.496693,1.732688,5.528418e+04,3.428809,...,333.981201,1.107430e+05,5774.407227,5.258323e+04,306.407013,5662.850098,2645.757080,1462.057739,0.606934,2222.071777
min,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,1.000011e+06,0.000000,...,0.000000,0.000000e+00,-19968.000000,0.000000e+00,-19968.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,268.000000,21.000000,0.000000,0.000000,0.0,0.000000,0.000000,5.000000,1.048348e+06,3.000000,...,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1254.000000,43.000000,0.000000,0.000000,0.0,0.000000,1.000000,5.000000,1.095931e+06,6.000000,...,0.000000,9.308000e+03,9164.000000,0.000000e+00,0.000000,3192.000000,0.000000,0.000000,0.000000,0.000000
75%,1654.000000,62.000000,0.000000,37.000000,0.0,0.000000,1.000000,7.000000,1.143886e+06,9.000000,...,0.000000,2.311764e+04,12500.000000,3.147150e+03,0.000000,12500.000000,1075.199951,863.039978,0.000000,0.000000
max,50654.000000,80.000000,100.000000,132.000000,0.0,1.000000,1.000000,10.000000,1.191752e+06,11.000000,...,5000.000000,2.189985e+07,19222.140625,1.049953e+07,1000.000000,12500.000000,440800.531250,9783.839844,3.050000,440641.937500